channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=22.3.1
- pip:
  - mlflow
  - cffi==1.15.1
  - defusedxml==0.7.1
  - fsspec==2022.11.0
  - pandas==1.5.2
  - pillow==9.3.0
  - pydot==1.4.2
  - scipy==1.9.3
  - tensorflow-intel==2.11.0
  - tensorflow==2.11.0
name: mlflow-env
